### PR TITLE
Added optional settings

### PR DESCRIPTION
**Pull request by delneg**
Define custom active class and strictness

### CODE REVIEW

**Comment by valerymelou** [comment]
Good job, thanks. Will be happy to merge once the tests are green.

**Comment by valerymelou** [comment]
And I think the same settings are not always applied site wise, so it should always be possible to customize the active class and the strictness right from the template, don't you think?

**Comment by delneg** [comment]
Well maybe but since the tag is repeated multiple times in the template it would be annoying to set it to strict/nonstrict each time we use the tag.
I think both methods should be possible

**Comment by valerymelou** [comment]
Yes, that's why the tag should keep accepting `active_class` and `strict` arguments from the template and both should have their default values set to the ones from settings.

**Comment by delneg** [comment]
Okay, that seems like the best decision

**Pull request closed without merging**
