### PR TITLE
Correctly capture the url kwargs

### PR DESCRIPTION
**Pull request by Frodothedwarf**
I found a bug where if a path has values it needs to capture, it would never capture it, because Django does not pass these to kwargs (at least in newer versions of Django).

This change correctly captures the kwargs from the request and updates the kwargs dict, so the reverse function can reverse the url correctly.

Correctly capture the kwargs from the url, needed if it should reverse against url paths with variables defined in Django.

### CODE REVIEW

**Comment by Frodothedwarf** [comment]
@valerymelou can you please take a look at this pr?

**Comment by Frodothedwarf** [comment]
> @valerymelou can you please take a look at this pr?

@valerymelou I think this is a very important pr, and needs to be merged. Fixes for example sidebar nav, when you are on a page that requires url variables.

**Review by valerymelou — APPROVED** [review]

**Comment by valerymelou** [comment]
Thanks @Frodothedwarf and sorry for the delay.

**Comment by Frodothedwarf** [comment]
> Thanks @Frodothedwarf and sorry for the delay.

Thanks, no problem for the delay.
Just to be sure, are you going to release a new release on pypi?

**Comment by Frodothedwarf** [comment]
> > Thanks @Frodothedwarf and sorry for the delay.
> 
> Thanks, no problem for the delay. Just to be sure, are you going to release a new release on pypi?

Just tagging @valerymelou

**Comment by Frodothedwarf** [comment]
@valerymelou if you like I can take over the project, or be a maintainer?

**Comment by valerymelou** [comment]
@Frodothedwarf happy to have you as a maintainer.

**Comment by Frodothedwarf** [comment]
@valerymelou would be happy to help maintaining the project.

**Pull request merged**
